name: Update Translation Pages

on: workflow_call

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: wiki
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run Compare Strings script
      run: |
        python ./src/scripts/compare-strings.py -format workflow -verbose ./src/UI.Main/Resources/Strings ./src/UI.Main/Resources/Strings/en.xaml
        python ./src/scripts/update-translation-summary.py translationStatus.json ./wiki/Translating.md
        ls
      shell: pwsh
    - name: Apply wiki changes
      run: |
        # Overwrite existing wiki translation table
        Copy-Item translationTable.md -Destination ./wiki/Translation-Status.md
        Copy-Item translationUpdatedSummary.md -Destination ./wiki/Translating.md

        # Configure git, commit, and push
        cd wiki
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        # Will only pick up changes
        git add .
        git diff-index --quiet HEAD || git commit -m "Translation status updated by $env:GITHUB_RUN_ID" && git push
      shell: pwsh